### ISSUE TITLE
Doesn't work with Aion solo pool

### ISSUE THREAD

**Issue by iamyulong** [aionnetwork/aionr#19]
Full log from the Aion solo pool:

```
aion@adl-aion1:~/ARRT/pool$ ./run_quickstart.sh
9056:C 24 May 08:47:46.885 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
9056:C 24 May 08:47:46.886 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=9056, just started
9056:C 24 May 08:47:46.886 # Configuration loaded
function verify() { [native code] }
2019-05-24 08:47:47 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2019-05-24 08:47:47 [Master]    [CLI] CLI listening on port 17117
2019-05-24 08:47:47 [Master]    [PoolSpawner] Spawned 1 pool(s) on 1 thread(s)
function verify() { [native code] }
2019-05-24 08:47:47 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2019-05-24 08:47:47 [Pool]      [aion] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2019-05-24 08:47:47 [Pool]      [aion] (Thread 1) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getinfo","params":[],"id":1558702067528}
Reponse Data: Supplied content type is not allowed. Content-Type: application/json is required

2019-05-24 08:47:47 [Switching] [Setup] (Thread 1) Switching "switch0" listening for equihash on port 3333 into aion
2019-05-24 08:48:47 [Switching] [Connect] (Thread 1) Connection to switch0 from ::ffff:127.0.0.1 on 3333 routing to aion
/home/aion/ARRT/pool/libs/poolWorker.js:279
                            pools[currentPool].getStratumServer().handleNewClient(socket);
                                                                 ^

TypeError: Cannot read property 'handleNewClient' of undefined
    at Server.<anonymous> (/home/aion/ARRT/pool/libs/poolWorker.js:279:66)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Object.onconnection (net.js:1570:8)
    at onconnection (internal/cluster/child.js:178:12)
    at Worker.onmessage (internal/cluster/child.js:44:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
2019-05-24 08:48:47 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
function verify() { [native code] }
2019-05-24 08:48:49 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2019-05-24 08:48:49 [Pool]      [aion] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2019-05-24 08:48:49 [Pool]      [aion] (Thread 1) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getinfo","params":[],"id":1558702129613}
Reponse Data: Supplied content type is not allowed. Content-Type: application/json is required

2019-05-24 08:48:49 [Switching] [Setup] (Thread 1) Switching "switch0" listening for equihash on port 3333 into aion
```

**Comment by MiaoShi09** [comment]
The solo mining pool code at batch [patch-jsonrpc](https://github.com/aionnetwork/aion_miner/tree/patch-jsonrpc) to work for both kernels. So far this branch has not been pull into master.

**Comment by iamyulong** [comment]
Thanks for your swift response. I will try that branch and post any issues I encounter.

**Comment by iamyulong** [comment]
Just another error popped out after switching to the branch.

```
2019-05-24 09:22:00 [Switching]	[Connect] (Thread 1) Connection to switch0 from ::ffff:127.0.0.1 on 3333 routing to aion
/home/aion/ARRT/aion_miner/aion_solo_pool/libs/poolWorker.js:149
                                return r.response.isvalid
                                                  ^

TypeError: Cannot read property 'isvalid' of undefined
    at /home/aion/ARRT/aion_miner/aion_solo_pool/libs/poolWorker.js:149:51
    at Array.filter (<anonymous>)
    at /home/aion/ARRT/aion_miner/aion_solo_pool/libs/poolWorker.js:148:51
    at /home/aion/ARRT/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:184:17
    at wrapper (/home/aion/ARRT/aion_miner/aion_solo_pool/node_modules/async/dist/async.js:270:20)
    at iteratorCallback (/home/aion/ARRT/aion_miner/aion_solo_pool/node_modules/async/dist/async.js:497:17)
    at /home/aion/ARRT/aion_miner/aion_solo_pool/node_modules/async/dist/async.js:323:20
    at itemFinished (/home/aion/ARRT/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:166:17)
    at /home/aion/ARRT/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:178:17
    at parseJson (/home/aion/ARRT/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:86:17)
```

**Comment by iamyulong** [comment]
Never mind. The `--user` has to be a valid Aion address. Now it's working.

It would be nice to have a tutorial on how to set up "Aion rust kernel + Aion solo pool + EWBF miner".
