### ISSUE TITLE
get_chain_info panic

### ISSUE THREAD

**Issue by aion-camus** [aionnetwork/aionr#54]
> os & version: ubuntu 18.04
> branch: dev
---------------------------------------------------------------------------
stack backtrace:
   0:     0x55a92178c11c - backtrace::backtrace::trace::h61547d182043fd14
   1:     0x55a92178b0d2 - <backtrace::capture::Backtrace as core::default::Default>::default::h78feaee0be4a90ff
   2:     0x55a92178b148 - backtrace::capture::Backtrace::new::h2d6d4843fc894739
   3:     0x55a9212005aa - panic_hook::panic_hook::h1b02266b6ad6b97f

Thread '<unnamed>' panicked at 'get_chain_info', libcore/option.rs:960

appears occasionally during shutdown

**Comment by aion-camus** [comment]
stack backtrace:
   0:     0x55a2e00b71ec - backtrace::backtrace::trace::h1430ff41323b0e43
   1:     0x55a2e00b61a2 - <backtrace::capture::Backtrace as core::default::Default>::default::h4c73ad1b64946eb7
   2:     0x55a2e00b6218 - backtrace::capture::Backtrace::new::ha2d025e79db68a5b
   3:     0x55a2dfb010aa - panic_hook::panic_hook::h3d1149545cb89668
   4:     0x55a2e0139463 - std::panicking::rust_panic_with_hook::he4c3a67f6258a8f9
                        at libstd/panicking.rs:515
   5:     0x55a2e01391b9 - std::panicking::continue_panic_fmt::h156c04b2aea348c7
                        at libstd/panicking.rs:426
   6:     0x55a2e0138ed5 - rust_begin_unwind
                        at libstd/panicking.rs:337
   7:     0x55a2e019a18b - core::panicking::panic_fmt::h0e6d5c6fb2a34dd6
                        at libcore/panicking.rs:92
   8:     0x55a2e018cad1 - core::option::expect_failed::h388c78b66d038dc6
                        at libcore/option.rs:960
   9:     0x55a2dfbf5ffb - acore::sync::storage::SyncStorage::get_chain_info::h173a3ba9200c5fe7
  10:     0x55a2dfb21443 - acore::sync::handler::status_handler::StatusHandler::handle_status_req::h27a705fe0867f95f
  11:     0x55a2dfc1ab13 - acore::sync::SyncMgr::handle::h3137cab8ab2d48b4
  12:     0x55a2dfccbe85 - p2p::NetManager::handle::hfed1c1a22358167d
  13:     0x55a2dfcdd53e - <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::h6551ee777d96a342
  14:     0x55a2dfcd2c07 - <futures::future::chain::Chain<A, B, C>>::poll::hab4fff404a44bd20
  15:     0x55a2dfd0acff - futures::task_impl::std::set::h57ce1b8e4ae56a4d
  16:     0x55a2dfd0c225 - <futures::task_impl::Spawn<T>>::poll_future_notify::h4623489ec804c2dd
  17:     0x55a2dfd0eed0 - std::panicking::try::do_call::h3de26c0899feb7d7
  18:     0x55a2e0161469 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  19:     0x55a2dfd0de29 - tokio_threadpool::task::Task::run::hd79b67cb91ebd7b6
  20:     0x55a2dfd06325 - tokio_threadpool::worker::Worker::run_task::h475783947089af23
  21:     0x55a2dfd057ef - tokio_threadpool::worker::Worker::run::he02da3faf588ba14
  22:     0x55a2dfd0d466 - <std::thread::local::LocalKey<T>>::with::h65017ae9ccfe466d
  23:     0x55a2dfd0d5aa - <std::thread::local::LocalKey<T>>::with::h7a1563539e7bd8c6
  24:     0x55a2dfd0f651 - std::sys_common::backtrace::__rust_begin_short_backtrace::h687b703789da33b8
  25:     0x55a2dfd0ef1b - std::panicking::try::do_call::h7ce3a6acbe8e64b6
  26:     0x55a2e0161469 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  27:     0x55a2dfd1098c - <F as alloc::boxed::FnBox<A>>::call_box::h2f548fe76a56b5a4
  28:     0x55a2e013631a - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output=R> + 'a> as core::ops::function::FnOnce<A>>::call_once::h75e539106a648d39
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread::h88a639c99862a9f5
                        at libstd/sys_common/thread.rs:24
  29:     0x55a2e013a045 - std::sys::unix::thread::Thread::new::thread_start::h7d7a420a78cfa84d
                        at libstd/sys/unix/thread.rs:90
  30:     0x7f76861056da - start_thread
  31:     0x7f7685c1688e - __clone
  32:                0x0 - <unknown>

thread '<unnamed>' panicked at 'get_chain_info', libcore/option.rs:960

This is a bug. Help us report here:
https://github.com/aionnetwork/aionr/issues/new
2019-09-03 15:20:09 Shutdown.
